### PR TITLE
Realtime bus updates

### PR DESCRIPTION
**Pull request by haggaie**
Hi,

I think my branch with realtime bus updates is mature enough for other people to see it :)
I still have other ideas on how to improve this feature, but it would be nice to get some feedback.
What do you think?

### CODE REVIEW

**Comment by lutzky** [comment]
Hey there,

After a long time of paying absolutely no attention to this, I finally took a look... it doesn't seem to do anything (there's just the list of companies), and the test fails. How am I supposed to use it?

**Comment by haggaie** [comment]
I'll take a look at the test. I think the first time you open it, the list of bus lines is downloaded, and afterwards you can press menu->refresh to redownload. Then you'll have a list of buses under the repsective company in the activity, and clicking on such a bus-line will show its current positions. Let me know if that doesn't work.

**Comment by haggaie** [comment]
Can you write specifically which test failed, and what was the result? I ran the tests again today, and didn't get any failures.

**Comment by lutzky** [comment]
After rerunning the test, it seems to work fine. The UI requires a refresh,
but then also seems to work. I'm thinking that it doesn't work on weekends
(and fails the unit tests as well)... good thing I took a day off.
By the way, I intend to add ads to the Play Store version. I'll keep the
mainline branch ad-free for devs.

On Sun, Jul 22, 2012 at 8:26 AM, Haggai Eran <
reply@reply.github.com

> wrote:
> 
> Can you write specifically which test failed, and what was the result? I
> ran the tests again today, and didn't get any failures.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lutzky/TransportDroidIL/pull/15#issuecomment-7158925

## 

"Any instrument is just a vehicle to express who you are and your
relationship to the world. No matter what level you’re doing it on, playing
music is an opportunity to give something to the world."
—Flea

Ohad Lutzky

**Pull request merged**
